name: python

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker-options: --platform linux/arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          working-directory: cli
          args: --release --out dist
          manylinux: manylinux_2_28
          docker-options: ${{ matrix.platform.docker-options }}
          # https://github.com/PyO3/maturin-action/issues/249
          # sccache: "true"
          before-script-linux: ${{ matrix.platform.before-script }}
